CREATE TABLE IF NOT EXISTS klines_1m (
  market TEXT NOT NULL,
  bucket TIMESTAMPTZ NOT NULL,
  start TIMESTAMPTZ NOT NULL,
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  volume NUMERIC NOT NULL DEFAULT 0,
  quote_volume NUMERIC NOT NULL DEFAULT 0,
  trades INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (market, bucket)
);

CREATE TABLE IF NOT EXISTS klines_1h (
  market TEXT NOT NULL,
  bucket TIMESTAMPTZ NOT NULL,
  start TIMESTAMPTZ NOT NULL,
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  volume NUMERIC NOT NULL DEFAULT 0,
  quote_volume NUMERIC NOT NULL DEFAULT 0,
  trades INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (market, bucket)
);

CREATE TABLE IF NOT EXISTS klines_1w (
  market TEXT NOT NULL,
  bucket TIMESTAMPTZ NOT NULL,
  start TIMESTAMPTZ NOT NULL,
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  volume NUMERIC NOT NULL DEFAULT 0,
  quote_volume NUMERIC NOT NULL DEFAULT 0,
  trades INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (market, bucket)
);
